name: 'Publish All Modules'
description: 'Publishes all modules'
inputs:
  sonatype_usr:
    description: 'Sonatype user'
    required: true
    default: ''
  sonatype_pwd:
    description: 'Sonatype password'
    required: true
    default: ''
  signing_key_id:
    description: 'Signing key id'
    required: true
    default: ''
  signing_key_pwd:
    description: 'Signing key password'
    required: true
    default: ''
  signing_key_file:
    description: 'Signing key file'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        ./gradlew clean \
          :AmericanExpress:publishToSonatype \
          :BraintreeCore:publishToSonatype \
          :BraintreeDataCollector:publishToSonatype \
          :Card:publishToSonatype \
          :GooglePay:publishToSonatype \
          :LocalPayment:publishToSonatype \
          :PayPal:publishToSonatype \
          :SharedUtils:publishToSonatype \
          :ThreeDSecure:publishToSonatype \
          :UnionPay:publishToSonatype \
          :Venmo:publishToSonatype \
          :SamsungPay:publishToSonatype \
          :SEPADirectDebit:publishToSonatype \
          :PayPalNativeCheckout:publishToSonatype \
      shell: bash
      env:
        SONATYPE_USERNAME: ${{ inputs.sonatype_usr }}
        SONATYPE_PASSWORD: ${{ inputs.sonatype_pwd }}
        SIGNING_KEY_ID: ${{ inputs.signing_key_id }}
        SIGNING_KEY_PASSWORD: ${{ inputs.signing_key_pwd }}
        SIGNING_KEY_FILE: ${{ inputs.signing_key_file }}
