name: Setup Java 8
description: 'Sets up Java 8'
runs:
  using: "composite"
  steps:
    - name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
