#!/usr/bin/env bash

command_name="$1"

case $command_name in
  lint)
    ./gradlew clean lint
    ./gradlew detekt --auto-correct
    ;;
  unit_tests)
    ./gradlew --continue clean testRelease
    ;;
  integration_tests)
    ./gradlew --continue connectedAndroidTest
    ;;
esac

