import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
//    alias libs.plugins.dokka
}

android {
    namespace "com.braintreepayments.api.datacollector"
    compileSdk rootProject.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion

        consumerProguardFiles 'proguard.pro'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    lintOptions {
        textReport true
        textOutput 'stdout'
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            all {
                jvmArgs '-noverify'
            }
        }
    }

    buildTypes {
        debug {
            testCoverageEnabled true
        }
    }

    compileOptions {
        sourceCompatibility versions.javaSourceCompatibility
        targetCompatibility versions.javaTargetCompatibility
    }

    kotlinOptions {
        jvmTarget = versions.javaTargetCompatibility.toString()
    }
}

tasks.register('shadowJar',ShadowJar){
    from zipTree(file('libs/android-magnessdk-5.6.0.jar'))
    relocate 'a/', 'magnes/a/'
    archiveBaseName.set('android-magnessdk-fixed-5.6.0')
//    destinationDirectory.set(file("${project.rootDir}/DataCollector/libs"))
}

// 挂载生命周期：确保在 Android 开始合并 Dex 之前，我们的修复任务已经把 JAR 包生产好了
tasks.configureEach {
    if (it.name.startsWith('mergeDex') || it.name.startsWith('process') || it.name.startsWith('compile')){
        dependsOn 'shadowJar'
    }
}

dependencies {
    implementation files(tasks.named('shadowJar'))
//    implementation files('libs/android-magnessdk-5.6.0.jar')

    implementation libs.androidx.annotation
    compileOnly project(':BraintreeCore')

    testImplementation libs.robolectric
    testImplementation libs.mockito.core
    testImplementation libs.androidx.test.core
    testImplementation libs.json.assert
    testImplementation libs.mockito.core
    testImplementation libs.mockk
    testImplementation libs.test.parameter.injector
    testImplementation libs.coroutines.test

    testImplementation project(':TestUtils')

    androidTestImplementation libs.androidx.test.rules
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.appcompat
    androidTestImplementation project(':TestUtils')
}

// region signing and publishing

project.ext.name = "data-collector"
project.ext.pom_name = "data-collector"
project.ext.group_id = "com.braintreepayments.api"
project.ext.version = rootProject.version
project.ext.pom_desc = "Fraud tools for Braintree integrations on Android."

// endregion
