name: Deploy to Preview Channel

on:
  push:
    branches:
      - paypal-app-switch-feature
      - firebase-publish
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: ./.github/actions/setup
      - name: Assemble
        run: ./gradlew --stacktrace :demo:assembleRelease
      - name: Decrypt large secret
        run: ./.github/executables/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.FIREBASE_PRIVATE_KEY_GPG_PASSPHRASE }}
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: $HOME/secrets/braintree_demo_app.json
          expires: 30d
          projectId: braintree-demo-app